# -*- coding: utf-8 -*-
"""
Created on Tue May 29 14:19:19 2018

@author: u2362
"""

5 AGCC AGGAGG ATGCATTATAATTAAGACAT CCTCCT CNATGCTGAAATTATA GC 3
3 TCGG TCCTCC TACGTAATATTAATTCTGTA GGAGGA GNTACGACTTTAATAT CG 5
