# -*- coding: utf-8 -*-
"""
Created on Tue May 29 14:19:19 2018

@author: u2362
"""

5 AGCC AGGAGG ATGCCATGTATAATTAAGA CATGAT CATGNCTGAAATTTGA GC 3
3 TCGG TCCTCC TACGGTACATATTAGTTCT GTAGGA GNTACGACTTTAATAT CG 5

  AGCC AGGAGG ATGCCCATGTATAATTAAGA CATCCT CNATGCTGAAATTATA GC