# -*- coding: utf-8 -*-
"""
Created on Tue May 29 14:19:19 2018

@author: u2362
"""

5 AGCC AGGAGG ATGCCATGTATAATTAAGA CATGAT CATGNCTGAAATTTGA GC 3
3 TCGG TCCTCC TACGGTACATATTAGTTCT GTAGGA GNTACGACTTTAATAT CG 5

  AGCC AGGAGG ATGCCCATGTATAATTAAGA CATCCT CNATGCTGAAATTATA GC
#normal
AGC CAG GAG GAT GCC ATG TAT AAT TAA GAC ATG ATC ATG NCT GAA ATT TGA  GC		
AG  CCA GGA GGA TGC CAT GTA TAA TTA AGA CAT GAT CAT GNC TGA AAT TTG AGC
A  GCC AGG AGG ATG CCA TGT ATA ATT AAG ACA TGA TCA TGN CTG AAA TTT GAG  C

#rev
GCT CAA ATT TCA GNC ATG ATC ATG TCT TAA TTA TAC ATG GCA TCC TCC TGG CT
GC TCA AAT TTC AGN CAT GAT CAT GTC TTA ATT ATA CAT GGC ATC CTC CTG GCT
G CTC AAA TTT CAG NCA TGA TCA TGT CTT AAT TAT ACA TGG CAT CCT CCT GGC T
